services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=sqlite+aiosqlite:///./data/garden_planner.db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - sqlite_data:/app/data  # SQLite database volume
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    working_dir: /backend
    depends_on:
      - db-init

  # Database initialization service
  db-init:
    build: ./backend
    volumes:
      - sqlite_data:/app/data
    env_file:
      - ./backend/.env
    command: uv run python -c "import asyncio; from models.database import init_database; asyncio.run(init_database())"
    restart: "no"

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local